apiVersion: v1
kind: Pod
metadata:
  name: tool-jan
  namespace: clinibench
spec:
  containers:
    - args:
        - while true; do sleep 30; done;
      command:
        - /bin/bash
        - -c
        - --
      image: debian
      name: tool
      volumeMounts:
        - mountPath: /data
          name: clinibench-pvc
        - mountPath: /merlin_ddx
          name: merlin-ddx-pvc
        - mountPath: /models
          name: model-volume
  volumes:
    - name: clinibench-pvc
      persistentVolumeClaim:
        claimName: clinibench-pvc
    - name: merlin-ddx-pvc
      persistentVolumeClaim:
        claimName: merlin-ddx-ckpts-pvc
    - name: model-volume
      persistentVolumeClaim:
        claimName: model-volume


