apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-server-mistral-large
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm-server-mistral-large
  template:
    metadata:
      labels:
        app: vllm-server-mistral-large
    spec:
      imagePullSecrets:
        - name: private-registry-auth
      containers:
        - name: vllm-server-mistral-large
          image: vllm/vllm-openai:v0.9.1  # For B200
          command:  ["python3", "-m",
                     "vllm.entrypoints.openai.api_server",
#                     "--model=Qwen/Qwen3-8B",
#                     "--model=meta-llama/Llama-3.3-70B-Instruct",
#                     "--model=mistralai/Mistral-Small-3.2-24B-Instruct-2506",
                     "--model=mistralai/Mistral-Large-Instruct-2407",
                     "--tokenizer-mode", "mistral",
                     "--config-format", "mistral",
                     "--load-format", "mistral",
#                     "--model=deepseek-ai/DeepSeek-R1-Distill-Qwen-32B",
#                     "--model=google/gemma-3-27b-it",
#                     "--model=Qwen/QwQ-32B",
#                     "--model=deepseek-ai/DeepSeek-R1",
#                     "--model=OpenMeditron/Meditron3-Qwen2.5-14B",
#                     "--model=google/medgemma-27b-text-it",
                     "--max-model-len=8192", # Our prompts should not exceed 8k tokens
                     "--tensor-parallel-size=8",
                     "--download-dir=/models",
          ]
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: "32"
              memory: "256Gi"
              nvidia.com/gpu: "8"
            requests:
              cpu: "4"
              memory: "32Gi"
              nvidia.com/gpu: "8"
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm  # Mount shared memory
            - name: model-volume
              mountPath: /models
          env:
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-token-secret
                  key: HF_TOKEN
            - name: NCCL_DEBUG
              value: "INFO"
#            - name: NCCL_IB_DISABLE
#              value: "1"
#            - name: NCCL_SOCKET_IFNAME
#              value: "eth0"
#            - name: NCCL_P2P_DISABLE
#              value: "1"
#            - name: NCCL_CUMEM_ENABLE
#              value: "1"
#            - name: GLOO_SOCKET_IFNAME
#              value: "eth0"
      nodeSelector:
        gpu: a100
#        kubernetes.io/hostname: cl-worker36
      volumes:
        - name: dshm  # Define shared memory volume
          emptyDir:
            medium: Memory
        - name: model-volume
          persistentVolumeClaim:
            claimName: model-volume

---
apiVersion: v1
kind: Service
metadata:
  name: vllm-server-mistral-large
spec:
  selector:
    app: vllm-server-mistral-large
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000